// Auto-generated from brick_lab.lua
const char *brick_lab_lua_module = "-- brick_labs.lua\n"
"\n"
"-- Base Device class: handles common device logic\n"
"local Device = {}\n"
"Device.__index = Device\n"
"\n"
"-- Create a new Device instance by UUID\n"
"function Device.new(uuid)\n"
"  local handle = brick.get_device_from_uuid(uuid)              -- Get device from C API\n"
"  assert(handle, \"Device not found: \" .. uuid)                 -- Ensure device exists\n"
"  return setmetatable({ uuid = uuid, handle = handle }, Device)\n"
"end\n"
"\n"
"-- Get the device type (e.g., LED_RGB, SERVO, etc.)\n"
"function Device:get_type()\n"
"  return self.handle.device_type\n"
"end\n"
"\n"
"-- Check if this device is an RGB LED device\n"
"function Device:is_rgb()\n"
"  return self:get_type() == brick.DEVICE_LED_RGB               -- Requires DEVICE_LED_RGB enum exposed to Lua\n"
"end\n"
"\n"
"-- DeviceRgb subclass: extends Device with RGB-specific methods\n"
"local DeviceRgb = {}\n"
"DeviceRgb.__index = DeviceRgb\n"
"setmetatable(DeviceRgb, { __index = Device })                  -- Inherit from Device\n"
"\n"
"-- Create a new RGB device, ensuring the device type matches\n"
"function DeviceRgb.new(uuid)\n"
"  local base = Device.new(uuid)\n"
"  assert(base:is_rgb(), \"Not an RGB LED device\")               -- Type check at runtime\n"
"  return setmetatable(base, DeviceRgb)\n"
"end\n"
"\n"
"-- Set the RGB LED to a specific color table: { red = X, green = Y, blue = Z }\n"
"function DeviceRgb:set_rgb(color)\n"
"  brick.send_command(self.uuid, brick.CMD_LED_RGB, color)      -- Send RGB command via C API\n"
"end\n"
"\n"
"-- Return the module: exposes both classes to users of require(\"brick_labs\")\n"
"return {\n"
"  Device = Device,\n"
"  DeviceRgb = DeviceRgb\n"
"}\n"
"";
